export const ADD_INGREDIENTS = "ADD_INGREDIENT";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";
